import esbuild from "esbuild";

const watch = process.argv.includes("--watch");

const context = await esbuild.context({
  entryPoints: ["main.ts"],
  bundle: true,
  external: ["obsidian"],
  format: "cjs",
  target: "es2020",
  sourcemap: false,
  platform: "browser",
  outfile: "main.js",
  banner: {
    js: "/* Generated by esbuild for Obsidian. */"
  }
});

if (watch) {
  await context.watch();
  console.log("Watching Folder Pin plugin...");
} else {
  await context.rebuild();
  await context.dispose();
  console.log("Built Folder Pin plugin.");
}
